name: Azure Deploy

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: Pastprep
  AZURE_WEBAPP_PACKAGE_PATH: '.'
  NODE_VERSION: '20.x'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: Install dependencies and sharp
      run: |
        npm ci
        npm install sharp

    - name: Build
      run: npm run build

    - name: Create deployment package
      run: |
        # Create deployment directory
        mkdir deployment
        
        # Copy standalone output
        cp -r .next/standalone/* deployment/
        
        # Copy public assets if directory exists
        if [ -d "public" ]; then
          mkdir -p deployment/public
          cp -r public/* deployment/public/ || true
        fi
        
        # Copy static files from .next/static
        mkdir -p deployment/.next/static
        cp -r .next/static/* deployment/.next/static/
        
        # Copy config
        cp next.config.mjs deployment/
        
        # Create startup script
        echo '#!/bin/bash
        cd /home/site/wwwroot
        node server.js' > deployment/startup.sh
        chmod +x deployment/startup.sh
        
        # Create zip with only required files
        cd deployment
        zip -r ../release.zip .

    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v3
      with:
        name: node-app
        path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v3
      with:
        name: node-app

    - name: 'Azure Login'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: 'Deploy to Azure WebApp'
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZUREWEBAPP_PUBLISHPROFILE }}
        package: release.zip