name: Deploy to Azure Web App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
    
    - name: Install dependencies
      run: |
        # Install all dependencies including devDependencies for build
        npm ci
        # Install additional required packages
        npm install sharp @radix-ui/colors
        
    - name: Build Next.js app
      run: |
        npm run build
        
    - name: Organize deployment files
      run: |
        # Create deployment package with only necessary files
        mkdir deployment
        cp -r .next deployment/
        cp -r public deployment/
        cp package.json deployment/
        cp package-lock.json deployment/
        cp next.config.mjs deployment/
        
        # Create production-only package.json
        node -e "const pkg=require('./package.json'); delete pkg.devDependencies; require('fs').writeFileSync('deployment/package.json', JSON.stringify(pkg, null, 2));"
    
    - name: Install production dependencies in deployment directory
      working-directory: deployment
      run: |
        # Install production dependencies including sharp
        npm ci --only=production --ignore-scripts
        npm install sharp @radix-ui/colors --save-prod
    
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'Pastprep'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: deployment
        
    - name: Configure startup command
      uses: azure/appservice-settings@v1
      with:
        app-name: 'Pastprep'
        app-settings-json: '[
          {
            "name": "WEBSITE_RUN_FROM_PACKAGE",
            "value": "1"
          },
          {
            "name": "SCM_DO_BUILD_DURING_DEPLOYMENT",
            "value": "false"
          },
          {
            "name": "NODE_ENV",
            "value": "production"
          }
        ]'
        mask-inputs: false