name: Deploy to Azure App Service

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Source
      uses: actions/checkout@v3
      
    - name: Set up Docker Buildx
      uses: docker-practice/actions-setup-buildx@master
      
    - name: Log in to Docker
      uses: docker-practice/actions-login@master
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Build and push Docker image
      uses: docker-practice/actions-build-and-push@master
      with:
        image: yousufahmed/pastprep
        tag: ${{ github.sha }}
        
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: pastprep
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        images: yousufahmed/pastprep:${{ github.sha }}